/* Generated by Yosys 0.53+70 (git sha1 e046e3cdb, clang++ 18.1.8 -fPIC -O3) */

module up_down_counter(clk, rst_n, up, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [3:0] _08_;
  wire [3:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input rst_n;
  wire rst_n;
  input up;
  wire up;
  sg13g2_nand2b_1 _13_ (
    .A_N(count[1]),
    .B(up),
    .Y(_00_)
  );
  sg13g2_nor2b_1 _14_ (
    .A(up),
    .B_N(count[1]),
    .Y(_01_)
  );
  sg13g2_xnor2_1 _15_ (
    .A(count[1]),
    .B(up),
    .Y(_02_)
  );
  sg13g2_xnor2_1 _16_ (
    .A(_08_[0]),
    .B(_02_),
    .Y(_09_[1])
  );
  sg13g2_a21oi_1 _17_ (
    .A1(count[0]),
    .A2(_00_),
    .B1(_01_),
    .Y(_03_)
  );
  sg13g2_xnor2_1 _18_ (
    .A(up),
    .B(count[2]),
    .Y(_04_)
  );
  sg13g2_xnor2_1 _19_ (
    .A(_03_),
    .B(_04_),
    .Y(_09_[2])
  );
  sg13g2_and4_1 _20_ (
    .A(count[1]),
    .B(up),
    .C(count[2]),
    .D(count[0]),
    .X(_05_)
  );
  sg13g2_nor4_1 _21_ (
    .A(count[1]),
    .B(up),
    .C(count[2]),
    .D(count[0]),
    .Y(_06_)
  );
  sg13g2_nor2_1 _22_ (
    .A(_05_),
    .B(_06_),
    .Y(_07_)
  );
  sg13g2_xnor2_1 _23_ (
    .A(count[3]),
    .B(_07_),
    .Y(_09_[3])
  );
  sg13g2_dfrbp_1 _24_ (
    .CLK(clk),
    .D(_08_[0]),
    .Q(count[0]),
    .Q_N(_08_[0]),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbp_1 _25_ (
    .CLK(clk),
    .D(_09_[1]),
    .Q(count[1]),
    .Q_N(_11_),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbp_1 _26_ (
    .CLK(clk),
    .D(_09_[2]),
    .Q(count[2]),
    .Q_N(_12_),
    .RESET_B(rst_n)
  );
  sg13g2_dfrbp_1 _27_ (
    .CLK(clk),
    .D(_09_[3]),
    .Q(count[3]),
    .Q_N(_10_),
    .RESET_B(rst_n)
  );
  assign _09_[0] = _08_[0];
endmodule
